# -*- coding: utf-8; indent-tabs-mode: nil; tab-width: 2; -*-

---
- name: (os=Ubuntu) Install Nginx
  apt: name=nginx state=present
  sudo: yes
  when: ansible_os_family == 'Debian' and ansible_distribution_release == 'trusty'

- name: Add site configs
  template: src=files{{ item }}/default dest={{ item }}/{{ project_name }} mode=0644
  sudo: yes
  with_items:
  - /etc/nginx/sites-available
  notify:
    - nginx_check_config
    - nginx_restart

- name: Make site symlinks
  file: src=/etc/nginx/sites-available/{{ project_name }}
        dest=/etc/nginx/sites-enabled/{{ project_name }} state=link
  sudo: yes
  notify:
    - nginx_check_config
    - nginx_restart

- name: Enable and start Nginx
  service: name=nginx state=started enabled=yes
